services:
  butty:
    build: .
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      BUTTY_DB_PATH: /data/db.sqlite
    volumes:
      - butty-data:/data
    restart: unless-stopped
  # butty-test:
  #   build: .
  #   ports:
  #     - "8002:8002"
  #   env_file:
  #     - .env.test
  #   environment:
  #     BUTTY_DB_PATH: /data/db.sqlite
  #   volumes:
  #     - butty-data-test:/data
  #   restart: unless-stopped

volumes:
  butty-data:
  # butty-data-test:
